### Register User
POST http://localhost:3000/register
Content-Type: application/json

{
  "username": "adam_richard",
  "name": "Adam Richard",
  "password": "richard_567",
  "gender": "male",
  "location": "Detroit"
}

### Login User (Generates JWT Token)
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "adam_richard",
  "password": "richard_567"
}

### Change Password (Protected Route - Requires JWT Token)
PUT http://localhost:3000/change-password
Content-Type: application/json
Authorization: Bearer <your_jwt_token_here>

{
  "username": "adam_richard",
  "oldPassword": "richard_567",
  "newPassword": "richard@123"
}

### Example Protected API (User Profile - Requires JWT Token)
GET http://localhost:3000/user/profile
Authorization: Bearer <your_jwt_token_here>
